name: Run examples

on: [push, pull_request]

env:
  CGO_ENABLED: 0

jobs:
  run:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
      - name: Install libffi
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install libffi
          export LD_LIBRARY_PATH=/opt/homebrew/opt/libffi/lib
      - name: Run example
        run: go run examples/simple/cos/main_unix.go
